try:
    raise ValueError("error")
except ValueError:
    print("except")

print("continue")
    
